import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadBridgeSchemas } from "./bridge-schemas.js";
import { loadProject } from "./config.js";
import type {
  BridgePropertyDef,
  BridgeSchema,
} from "./types.js";
import { GENERATED_DIR } from "./types.js";

function toPascalCase(name: string): string {
  return name
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function propertyTypeToTs(def: BridgePropertyDef): string {
  switch (def.type) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "object":
      return "Record<string, unknown>";
    case "array":
      return "unknown[]";
    default:
      return "unknown";
  }
}

function renderPropsInterface(
  interfaceName: string,
  props: Record<string, BridgePropertyDef> | undefined,
): string {
  const entries = Object.entries(props ?? {});
  if (entries.length === 0) {
    return `export type ${interfaceName} = Record<string, never>;`;
  }
  const lines = entries.map(([key, def]) => {
    const comment = def.description
      ? `  /** ${def.description.replace(/\*\//g, "*\\/")} */\n`
      : "";
    return `${comment}  ${JSON.stringify(key)}: ${propertyTypeToTs(def)};`;
  });
  return `export interface ${interfaceName} {\n${lines.join("\n")}\n}`;
}

function renderTypes(schemas: BridgeSchema[]): string {
  const chunks: string[] = [
    "/* eslint-disable */",
    "// Generated by @client-platform/hybrid — do not edit by hand.",
    "",
  ];
  const methodParams: string[] = [];
  const methodResults: string[] = [];
  const eventPayloads: string[] = [];

  for (const schema of schemas) {
    if (schema.kind === "method") {
      const paramsName = `${toPascalCase(schema.name)}Params`;
      const resultName = `${toPascalCase(schema.name)}Result`;
      chunks.push(renderPropsInterface(paramsName, schema.params));
      chunks.push("");
      if (schema.result) {
        chunks.push(
          `export type ${resultName} = ${propertyTypeToTs(schema.result)};`,
        );
      } else {
        chunks.push(`export type ${resultName} = void;`);
      }
      chunks.push("");
      methodParams.push(`  ${JSON.stringify(schema.name)}: ${paramsName};`);
      methodResults.push(`  ${JSON.stringify(schema.name)}: ${resultName};`);
    } else {
      const payloadName = `${toPascalCase(schema.name)}Payload`;
      chunks.push(renderPropsInterface(payloadName, schema.payload));
      chunks.push("");
      eventPayloads.push(`  ${JSON.stringify(schema.name)}: ${payloadName};`);
    }
  }

  chunks.push("export interface MethodParamsMap {");
  chunks.push(methodParams.length ? methodParams.join("\n") : "  // no methods");
  chunks.push("}");
  chunks.push("");
  chunks.push("export interface MethodResultMap {");
  chunks.push(methodResults.length ? methodResults.join("\n") : "  // no methods");
  chunks.push("}");
  chunks.push("");
  chunks.push("export type MethodName = keyof MethodParamsMap;");
  chunks.push("");
  chunks.push("export interface EventPayloadMap {");
  chunks.push(eventPayloads.length ? eventPayloads.join("\n") : "  // no events");
  chunks.push("}");
  chunks.push("");
  chunks.push("export type EventName = keyof EventPayloadMap;");
  chunks.push("");
  return `${chunks.join("\n")}\n`;
}

function renderHelpers(): string {
  return `/* eslint-disable */
// Generated by @client-platform/hybrid — do not edit by hand.
import type {
  EventName,
  EventPayloadMap,
  MethodName,
  MethodParamsMap,
  MethodResultMap,
} from "./types.js";

type BridgeTransport = {
  call: <N extends MethodName>(
    name: N,
    params: MethodParamsMap[N],
  ) => Promise<MethodResultMap[N]>;
  on: <N extends EventName>(
    name: N,
    handler: (payload: EventPayloadMap[N]) => void,
  ) => () => void;
};

const defaultTransport: BridgeTransport = {
  async call(name, params) {
    console.info("[hybrid:bridge.call]", name, params);
    return undefined as never;
  },
  on(name, handler) {
    const listener = (event: MessageEvent) => {
      const data = event.data as { type?: string; name?: string; payload?: unknown };
      if (data?.type === "hybrid-bridge-event" && data.name === name) {
        handler(data.payload as EventPayloadMap[typeof name]);
      }
    };
    globalThis.addEventListener?.("message", listener);
    return () => globalThis.removeEventListener?.("message", listener);
  },
};

let transport: BridgeTransport = defaultTransport;

export function setBridgeTransport(next: BridgeTransport): void {
  transport = next;
}

export const bridge = {
  call<N extends MethodName>(
    name: N,
    params: MethodParamsMap[N],
  ): Promise<MethodResultMap[N]> {
    return transport.call(name, params);
  },
  on<N extends EventName>(
    name: N,
    handler: (payload: EventPayloadMap[N]) => void,
  ): () => void {
    return transport.on(name, handler);
  },
};
`;
}

function renderIndex(): string {
  return `/* eslint-disable */
// Generated by @client-platform/hybrid — do not edit by hand.
export * from "./types.js";
export * from "./helpers.js";
`;
}

export async function runGenerateBridge(cwd: string): Promise<string[]> {
  const project = await loadProject(cwd);
  if (!project.product) {
    throw new Error("products.hybrid missing or invalid; run hybrid init");
  }

  const { schemas, issues } = await loadBridgeSchemas(
    cwd,
    project.product.bridgeSchemaDir,
  );
  if (issues.length > 0) {
    throw new Error(
      `bridge schema issues:\n${issues.map((i) => `  - ${i.file}: ${i.message}`).join("\n")}`,
    );
  }

  const outDir = path.join(cwd, GENERATED_DIR);
  await mkdir(outDir, { recursive: true });

  const models = schemas.map((s) => s.schema);
  const files: Array<[string, string]> = [
    ["types.ts", renderTypes(models)],
    ["helpers.ts", renderHelpers()],
    ["index.ts", renderIndex()],
  ];

  const written: string[] = [];
  for (const [name, contents] of files) {
    const filePath = path.join(outDir, name);
    await writeFile(filePath, contents, "utf8");
    written.push(path.relative(cwd, filePath));
  }
  return written;
}
