import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  defaultProductConfig,
  writeProjectManifest,
  writeWorkspaceConfig,
} from "./config.js";
import { pathExists } from "./fs-utils.js";
import {
  DEFAULT_BRIDGE_SCHEMA_DIR,
  DEFAULT_PRESET,
  DEFAULT_WEB_ENTRY,
} from "./types.js";

const SAMPLE_METHOD = {
  schemaVersion: "1",
  kind: "method",
  name: "getDeviceInfo",
  params: {},
  result: {
    type: "object",
    description: "Device metadata payload",
  },
} as const;

const SAMPLE_EVENT = {
  schemaVersion: "1",
  kind: "event",
  name: "appResume",
  payload: {
    timestamp: {
      type: "string",
      description: "ISO timestamp when the app resumed",
    },
  },
} as const;

export async function runInit(cwd: string, preset: string): Promise<string[]> {
  if (preset !== DEFAULT_PRESET) {
    throw new Error(`unsupported preset: ${preset} (supported: ${DEFAULT_PRESET})`);
  }

  const written: string[] = [];
  const product = defaultProductConfig(preset);

  const configPath = await writeWorkspaceConfig(cwd, product);
  written.push(path.relative(cwd, configPath) || path.basename(configPath));

  const manifestPath = await writeProjectManifest(cwd, {
    targets: ["webview"],
    tooling: ["vite"],
  });
  written.push(path.relative(cwd, manifestPath) || path.basename(manifestPath));

  const bridgeDir = path.join(cwd, DEFAULT_BRIDGE_SCHEMA_DIR);
  await mkdir(bridgeDir, { recursive: true });

  const methodFile = path.join(bridgeDir, "method.getDeviceInfo.json");
  const eventFile = path.join(bridgeDir, "event.appResume.json");
  for (const [file, value] of [
    [methodFile, SAMPLE_METHOD],
    [eventFile, SAMPLE_EVENT],
  ] as const) {
    if (!(await pathExists(file))) {
      await writeFile(file, `${JSON.stringify(value, null, 2)}\n`, "utf8");
      written.push(path.relative(cwd, file));
    }
  }

  const webEntry = path.join(cwd, DEFAULT_WEB_ENTRY);
  if (!(await pathExists(webEntry))) {
    await mkdir(path.dirname(webEntry), { recursive: true });
    await writeFile(
      webEntry,
      `// Web entry stub generated by @client-platform/hybrid\nexport function mountApp(root: HTMLElement): void {\n  root.textContent = "hybrid web";\n}\n`,
      "utf8",
    );
    written.push(path.relative(cwd, webEntry));
  }

  return written;
}
